.PHONY: default
ocaml: rpms
default: rpms
DIST?=.el7.centos
MOCK=planex-cache --mock-exe /usr/bin/mock --cachedirs=/rpmcache
FETCH_EXTRA_FLAGS=--mirror file:///distfiles/ocaml2
# DEPEND_EXTRA_FLAGS=--no-package-name-check
# Start generated by planex-init
include /usr/share/planex/Makefile.rules
# End generated by planex-init
