#!/bin/bash
#
#  xenopsd-xenlight        Startup script for xenopsd-xenlight service
#
# chkconfig: 2345 22 88
# description: Manages VMs via libxl

# Source function library.
. /etc/init.d/functions

RETVAL=0
PIDFILE=/var/run/xenopsd-xenlight.pid

prog=xenopsd-xenlight
exec=/usr/sbin/xenopsd-xenlight
lockfile=/var/lock/subsys/$prog

# Source config
if [ -f /etc/sysconfig/$prog ] ; then
    . /etc/sysconfig/$prog
fi

# Enable core dumps
DAEMON_COREFILE_LIMIT='unlimited'

start() {
	[ -x $exec ] || exit 5

	umask 077

        echo -n $"Starting xenopsd-xenlight: "
        daemon --pidfile="$PIDFILE" $exec --pidfile "$PIDFILE" --config /etc/xenopsd.conf --daemon true $XENOPSD_XENLIGHT_OPTIONS
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch $lockfile
        return $RETVAL
}
stop() {
        echo -n $"Shutting down xenopsd-xenlight: "
        killproc -p "$PIDFILE" $exec
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $lockfile
        return $RETVAL
}
rhstatus() {
        status -p "$PIDFILE" -l $prog $exec
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  reload)
        exit 3
        ;;
  force-reload)
        restart
        ;;
  status)
        rhstatus
        ;;
  condrestart|try-restart)
        rhstatus >/dev/null 2>&1 || exit 0
        restart
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|condrestart|try-restart|reload|force-reload|status}"
        exit 3
esac

exit $?
